name: Workflow Filters and Activities

on:
    push:
        branches:
          - main
          - '!feature/*'

    pull_request:
        types:
          - opened
          - closed
        paths-ignore:
          - README.md
        branches:
          - main

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: Show Event
              run: |
                 echo ""This workflow ran for event: ${{ github.event_name }}""